version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: financial_db
    ports:
      - "5432:5432"
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
