SQL: "Convert this natural language query to a valid PostgreSQL SQL query for the stock_prices table (columns: ticker, date, close_price, pe_ratio, volume). Return only the SQL code: {query}"
Chat: "Provide a concise summary of the financial report based on this query. Keep it under 100 words: {query}"
Orchestrator: "Analyze this user query and return a JSON object with 'intents': ['sql', 'chat'] based on keywords like 'stock' for sql, 'summary' for chat: {query}"
